### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [figpii/figpii-gtm-template#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on data.accessKey when generating the url
const src = data.accessKey;
var url = 'https://tracking-cdn.figpii.com/' + src + '.js';

**Comment by reza-jalaei** [comment]
Thank you for your time, I have fixed the mentioned issue, can you please check? 
Thanks again!

**Comment by reza-jalaei** [comment]
@praveena-pappu Thank you for your time, I have fixed the mentioned issue, can you please check?
Thanks again!

**Comment by reza-jalaei** [comment]
Hey @praveena-pappu any updates for me?
